### ISSUE TITLE
Copycats+ Update destroys Trains when disassembled

### ISSUE THREAD

**Issue by M3veronMast3r** [forest-cat/create-trains#3]
The copycats+ Update to 2.0.0 and further creates an Major Problem when its about disassembling Trains. The Trains will not disassemble even after a few clicks and if you spam click it the trains activates the self destruction that almost nothing is left. Please downgrade Mod to the old working Version. Thanks :D

**Comment by forest-cat** [comment]
Fixed with: [Modpack v1.6.1 Copycat Hotfix](https://github.com/forest-cat/create-trains/releases/tag/v1.6.1)
